Add the possibility to upload images to a company.
EdiOancea/ferret-front pull request #11
Opened 2019-06-11 12:26 UTC by laurandarius

2019-06-11 12:27 UTC, laurandarius commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add the possibility to upload images to a company.](https://trello.com/c/G2tLhjmR/8-add-the-possibility-to-upload-images-to-a-company)

2019-06-20 06:47 UTC, lgnstn requested changes

2019-06-20 06:47 UTC, lgnstn commented on app/containers/ImageInput/index.js
> +    this.showFileUpload = this.showFileUpload.bind(this);
Please avoid using `bind` (it creates a new function every time and slows down the app). You can use `(...params) => this.showFileUpload(...params)` instead.

2019-06-20 06:47 UTC, lgnstn commented on app/components/ImageInput/index.js
> +      <input
Why do you have both a text input and a file input? You need only the file input.

2019-06-20 06:47 UTC, lgnstn commented on app/components/ImageInput/index.js
> +      InputProps={{
`InputProps` should start with a lower case letter, `inputProps`.

2019-06-20 06:47 UTC, lgnstn commented on app/services/addCompanyRequest.js
> +  formData.append('name', data.name);
You can make this code more flexible and open to changes if you iterate through all the keys of the data object and append them to the form.

2019-06-20 09:03 UTC, laurandarius commented
@lgnstn updated.

2019-06-24 06:48 UTC, lgnstn approved these changes

2019-06-24 06:48 UTC, merged