Add possibility to add review to a company.
EdiOancea/ferret-front pull request #13
Opened 2019-06-19 11:01 UTC by laurandarius

2019-06-19 11:03 UTC, laurandarius commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add the possibility to add a review to a company.](https://trello.com/c/3WL6gXwi/10-add-the-possibility-to-add-a-review-to-a-company)

2019-06-20 07:10 UTC, lgnstn requested changes

2019-06-20 07:10 UTC, lgnstn commented on app/components/CompanyReview/index.js
> +    hasReviewed,
Please rename it `wasReviewed`.

2019-06-20 07:10 UTC, lgnstn commented on app/containers/CompanyReview/actions.js
> +export const setHasReviewed = () => ({
I don't think you need this action. You can set this flag when add review success happens.

2019-06-20 07:10 UTC, lgnstn commented on app/containers/CompanyReview/index.js
> +        type: 'comment',
Shouldn't type be `text`?

2019-06-20 07:10 UTC, lgnstn commented on app/containers/CompanyReview/index.js
> +      ...state,
Have you tested this? If you add this line here, the last one, it should overwrite the previous lines, so the state will never change.

2019-06-20 07:10 UTC, lgnstn commented on app/containers/CompanyReview/index.js
> +          this.props.onSubmit({
When you use props values, define them as the first thing in the function, like this: `const { onSubmit, loggedUserId, companyId, rating, ... } = this.props;`.

2019-06-20 07:10 UTC, lgnstn commented on app/containers/CompanyReview/reducer.js
> +      return state.set('hasReviewed', action.hasReviewed);
This value should be saved in the company. Maybe you should update the API so it returns whether the logged use has reviewed a company or not.

2019-06-20 07:10 UTC, lgnstn commented on app/containers/CompanyReview/reducer.js
> +  canComment: false,
This shouldn't be in redux. We talked about this and agreed to keep this information in the component state.

2019-06-20 07:10 UTC, lgnstn commented on app/containers/CompanyReview/saga.js
> +    yield put(setHasReviewed());
As I said before, you don't need this one.

2019-06-24 06:33 UTC, laurandarius commented
@lgnstn updated.

2019-06-24 06:57 UTC, lgnstn approved these changes

2019-06-24 06:58 UTC, merged