Fix getUserRequest which expects logged user id.
EdiOancea/ferret-front pull request #17
Opened 2019-06-28 14:37 UTC by laurandarius

2019-06-28 14:37 UTC, laurandarius commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix login action redirect and getUserRequest from UserPage component.](https://trello.com/c/WLNKW8fL/15-fix-login-action-redirect-and-getuserrequest-from-userpage-component)

2019-07-16 06:52 UTC, lgnstn requested changes

2019-07-16 06:52 UTC, lgnstn commented on app/containers/App/reducer.js
> +      const lsToken = ls.get('token');
You shouldn't read the token from local storage here, in the reducer. The reducers should be pure functions (google it :) ). You read the local storage in the action function (you can use thunk middleware) and then dispatch another action that gets processed here, in the reducer, in order to set the token in the state.

2019-07-16 06:52 UTC, lgnstn commented on app/containers/App/actions.js
> +  type: LOAD_TOKEN,
Here you could read the local storage and then dispatch another action with the value of the token.

2019-07-22 09:49 UTC, laurandarius commented
@lgnstn updated.

2019-07-24 07:38 UTC, lgnstn requested changes

2019-07-24 07:38 UTC, lgnstn commented on app/configureStore.js
> +  const middlewares = [sagaMiddleware, routerMiddleware(history), thunk];
`thunk` should be the first middleware because it is the only one which knows what to do with functions.

2019-07-24 07:38 UTC, lgnstn commented on app/containers/App/actions.js
> +      dispatch(storeUserId(id));
Here I think you should also validate the token by making a request to the api to fetch the logged user, then you can store the whole user object in state.

2019-07-24 07:38 UTC, lgnstn commented on app/containers/SignInForm/actions.js
> +    const { id } = parseJwt(token);
Please define the variables at the beginning of the function/block.

2019-07-25 10:20 UTC, laurandarius commented
@lgnstn updated.

2019-07-26 08:05 UTC, lgnstn requested changes

2019-07-26 08:05 UTC, lgnstn commented on app/containers/App/actions.js
> +      dispatch(storeUserId(id));
Do you still need this line?

2019-07-26 08:05 UTC, lgnstn commented on app/containers/App/index.js
> +import saga from 'containers/UserPage/saga';
I think you should change the location of this saga. It is used here now, so please move it in this folder.

2019-07-26 08:05 UTC, lgnstn commented on app/containers/App/reducer.js
> +      return state.setIn(['loggedUser', 'meta'], userMeta);
You will fetch users from the api in other cases too, but it doesn't mean you have to store every user as the "logged" user. Please fix this.

2019-07-26 08:05 UTC, lgnstn commented on app/containers/UserPage/saga.js
> +    yield put(signOut());
Not in every situation you have to log out the user. Maybe the request returns 404, but it doesn't mean that the user is not logged in anymore. Only when you receive 401 you should log out. And this should happen for every request, not only for "get user". Do not mix things up, think well in what situations each function can be used and take into consideration every possibility.

2019-07-31 14:20 UTC, laurandarius commented
@lgnstn updated.

2019-08-01 05:28 UTC, lgnstn requested changes

2019-08-01 05:28 UTC, lgnstn commented on app/containers/App/actions.js
> +      dispatch(getLoggedUser(id));
I think you don't need the id here, do you?

2019-08-01 05:28 UTC, lgnstn commented on app/containers/SignInForm/actions.js
> +    dispatch(getLoggedUser(id));
Same thing, do you need the id here?

2019-08-01 05:28 UTC, lgnstn commented on app/containers/SignInForm/constants.js
> +export const EMPTY_SIGN_IN_ERROR_MESSAGE = 'EMPTY_SIGN_IN_ERROR_MESSAGE';
Why do you need this action?

2019-08-01 09:27 UTC, laurandarius commented
@lgnstn updated.

2019-08-02 07:22 UTC, lgnstn approved these changes

2019-08-02 07:23 UTC, merged