Fix format of the company address to be displayed in CompanyPage.
EdiOancea/ferret-front pull request #20
Opened 2019-07-31 14:26 UTC by laurandarius

2019-07-31 14:29 UTC, laurandarius commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix format of the company address to be displayed in CompanyPage.](https://trello.com/c/5BPr1LJK/18-fix-format-of-the-company-address-to-be-displayed-in-companypage)

2019-08-01 05:45 UTC, lgnstn requested changes

2019-08-01 05:45 UTC, lgnstn commented on app/containers/ViewCompany/actions.js
> +  company.address = `${address.streetName} ${address.streetNumber}, ap. ${
Don't do this here. Let the component that displays the address to decide how it looks like.

2019-08-01 09:23 UTC, laurandarius commented
@lgnstn updated.

2019-08-02 07:25 UTC, lgnstn requested changes

2019-08-02 07:25 UTC, lgnstn commented on app/components/Company/index.js
> +  const renderCompany = () => {
Please make this component a class. Then this method can be the `render` method. `renderSlideShow` will be a method in this class that you call from the `render` method.

2019-08-02 10:18 UTC, laurandarius commented
@lgnstn updated.

2019-08-06 06:09 UTC, lgnstn approved these changes

2019-08-06 06:09 UTC, merged