Login
EdiOancea/ferret-front pull request #3
Opened 2019-04-08 10:02 UTC by EdiOancea

2019-04-08 10:13 UTC, EdiOancea commented
@lgnstn updated

2019-04-08 10:47 UTC, EdiOancea commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create login page](https://trello.com/c/Q58KuMIY/2-create-login-page)

2019-04-09 07:52 UTC, lgnstn requested changes
Some comment are vague, so please tell me when you get there so I can give you more details.
Please use a better name for this PR (It can have the same name as the card).
Where are the tests? :)

2019-04-09 07:52 UTC, lgnstn commented on app/components/BorderWithIcon/BorderWithIcon.js
> +const BorderWithIcon = (props) => {
This is not a very good name. When I see this name I imagine that this component does something totally different than what it actually does.

2019-04-09 07:52 UTC, lgnstn commented on app/components/BorderWithIcon/BorderWithIcon.js
> +  return (
Don't forget about the empty line before `returns` :)

2019-04-09 07:52 UTC, lgnstn commented on app/components/BorderWithIcon/BorderWithIcon.js
> +        {children[0]}
Send this as a prop. You should not care about the structure of the children, just insert them in the structure of the component.

2019-04-09 07:52 UTC, lgnstn commented on app/components/BorderWithIcon/BorderWithIcon.js
> +      {children.map((child, i) => i != 0 ? child : null )}
Here you should have only `{children}`.

2019-04-09 07:52 UTC, lgnstn commented on app/components/SignInForm/SignInForm.js
> +        <form className={classes.form}>
This component should start at this line. The component wrapping the form don't have anything to do with the form. The idea is that you should be able to use this form in another context, which is not possible now.

2019-04-09 07:52 UTC, lgnstn commented on app/components/SignInForm/SignInForm.js
> +         <FormControl margin="normal" required fullWidth>
This is repetitive code which means it is time to create a new component.

2019-04-09 07:52 UTC, lgnstn commented on app/components/SignInForm/SignInForm.js
> +  classes: PropTypes.object.isRequired,
Add here all the props.

2019-04-09 07:52 UTC, lgnstn commented on app/containers/SignInPage/actions.js
> +  REQUEST_SIGN_IN,
Please follow this rules for actions names: `WHAT_HAPPENS`, `WHAT_HAPPENS_SUCCESS`, `WHAT_HAPPENS_FAILURE`. In your case would be `SIGN_IN`, `SIGN_IN_SUCCESS` and `SIGN_IN_FAILURE`.

2019-04-09 07:52 UTC, lgnstn commented on app/containers/SignInPage/actions.js
> +const requestSignIn = data => {
You can add here the `export` verb.

2019-04-09 07:52 UTC, lgnstn commented on app/containers/SignInPage/actions.js
> +export {
And drop this.

2019-04-09 07:52 UTC, lgnstn commented on app/containers/SignInPage/constants.js
> +export const REQUEST_SIGN_IN = 'app/SignInPage/REQUEST_SIGN_IN';
Probably you can use only `app/SIGN_IN`.

2019-04-09 07:52 UTC, lgnstn commented on app/containers/SignInPage/index.js
> +      {...{
Add one more level of indentation.

2019-04-09 07:52 UTC, lgnstn commented on app/containers/SignInPage/index.js
> +        onEmailChange: e => this.changeInput('email', e.target.value),
Don't pass the event so far up in the component tree. Call `onEmailChange` directly with the new value.

2019-04-09 07:52 UTC, lgnstn commented on app/containers/SignInPage/index.js
> +  token: makeSelectToken(),
Do you need the token here?

2019-04-09 07:52 UTC, lgnstn commented on app/containers/SignInPage/reducer.js
> +  token: "",
The token shouldn't be part of the SignInPage state because you need it in all the app.

2019-04-09 07:52 UTC, lgnstn commented on app/containers/SignInPage/reducer.js
> +  message: "",
Please use single quotes.

2019-04-09 07:52 UTC, lgnstn commented on app/containers/SignInPage/saga.js
> +    const response = yield fetch('https://enz0bi2bg7sak.x.pipedream.net', {
Please create a service that will handle api requests.

2019-04-09 07:52 UTC, lgnstn commented on app/containers/SignInPage/saga.js
> +  yield all([
You don't need the `all` function.

2019-04-09 07:52 UTC, lgnstn commented on app/containers/SignInPage/selectors.js
> +const makeSelectToken = () => createSelector(selectSignIn, signIn => signIn.get('token'));
I think `selectToke` is good enough. I think `make` is too much...

2019-04-24 07:17 UTC, lgnstn requested changes

2019-04-24 07:17 UTC, lgnstn commented on .travis.yml
> +wlanguage: node_js
I think that `w` shouldn't be here.

2019-04-24 07:17 UTC, lgnstn commented on __mocks__/isomorphic-fetch.js
> +  json: () => new Promise(resolve => resolve(value)),
This can also be written as `Promise.resolve(value)`.

2019-04-24 07:17 UTC, lgnstn commented on __mocks__/isomorphic-fetch.js
> +fetch.setValue = v => {
Ins't it better to call fetch in `before` with the value that you want to be returned? Using this `setValue` function  isn't the best option, IMHO.

2019-04-24 07:17 UTC, lgnstn commented on app/components/FormComponent/index.js
> +    classes,
This comes from the `withStyles` HOC, right?

2019-04-24 07:17 UTC, lgnstn commented on app/components/FormComponent/index.js
> +          {fields.map(field => {
Please move this code into a function.

2019-04-24 07:17 UTC, lgnstn commented on app/components/FormInput/index.js
> +const FormInput = props => {
This is a text input, so please change is name to `TextInput`.

2019-04-24 07:17 UTC, lgnstn commented on app/components/FormInput/tests/index.test.js
> +    expect(1).toBe(2);
This looks weird...

2019-04-24 07:17 UTC, lgnstn commented on app/components/SubmitErrorField/index.js
> +const SubmitErrorField = ({ errorMessage }) => <div> {errorMessage} </div>;
Please do not add spaces around `{errorMessage}`. This is not a field, it just displays the error message. I think you should find a better name for it.

2019-04-24 07:17 UTC, lgnstn commented on app/containers/SignInForm/reducer.js
> +  token: '',
I remember we talked about storing the `token` at a higher level in order to be available to the entire app.

2019-04-24 07:17 UTC, lgnstn commented on app/containers/SignInForm/saga.js
> +export default function* rootSaga() {
Do you really need this one?

2019-04-24 07:17 UTC, lgnstn commented on app/containers/SignInPage/index.js
> +const styles = theme => ({
Containers shouldn't contain styles. Please create another component or add this style to the `PaperFrame` component.

2019-04-24 07:17 UTC, lgnstn commented on app/services/signInRequest.js
> +  const res = await fetch('http://localhost:3001/api/signin', {
Please add a config with the base url. You want to easily change this from one env to another and also don't want to write this string in every file where you need it.

2019-05-06 06:07 UTC, lgnstn requested changes

2019-05-06 06:07 UTC, lgnstn commented on app/components/PaperFrame/index.js
> +        {text}
I would use `title`, or `headerText`. `text` is too generic and it is not obvious where it is going to be used.

2019-05-06 06:07 UTC, lgnstn commented on app/components/SignInPage/index.js
> +  <div className={classes.main}>
Could you please move this `div` into the `PaperFrame` component`?

2019-05-06 12:16 UTC, EdiOancea commented
@lgnstn  updated

2019-05-13 07:24 UTC, lgnstn approved these changes

2019-05-13 07:24 UTC, merged