Home page
EdiOancea/ferret-front pull request #4
Opened 2019-05-10 15:44 UTC by EdiOancea

2019-05-10 15:58 UTC, EdiOancea commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create an empty (for now) home page.](https://trello.com/c/NabmlPEB/5-create-an-empty-for-now-home-page)

2019-05-13 07:24 UTC, lgnstn commented
@EdiOancea Please resolve conflicts.

2019-05-13 13:54 UTC, EdiOancea commented
@lgnstn updated

2019-05-16 06:01 UTC, lgnstn requested changes

2019-05-16 06:01 UTC, lgnstn commented on app/components/UserContent/index.js
> +    <div> {props.name} </div>
Please remove the spaces

2019-05-16 06:01 UTC, lgnstn commented on app/containers/App/actions.js
> +import { IS_LOADING, IS_NOT_LOADING } from './constants';
These are not very good action names. They are more states than actions. Actions are "start loading/stop loading" or "show loader/hide loader", something like this.

2019-05-16 06:01 UTC, lgnstn commented on app/containers/PrivateRoute/index.js
> +    return (
Define in the beginning of the function all the props you need, like this: `const { path, token, Component, PrivateComponent } = this.props;`.

2019-05-16 06:01 UTC, lgnstn commented on app/containers/PrivateRoute/index.js
> +class PrivateRoute extends React.Component {
I don't like this very much. Route definitions should be simple, not too much logic there. I remember we talked about how you can handle "private" routes. Didn't it work that way?

2019-05-16 06:01 UTC, lgnstn commented on app/containers/SignInPage/index.js
> +    return this.props.token === '' ? (
You have this check implemented in too many places. It is too complicated to manage this way.

2019-05-16 06:01 UTC, lgnstn commented on app/containers/UserPage/actions.js
> +  type: GET_USER_FAILED,
Please use "FAILURE" instead of "FAILED". It doesn't match with the successful action. Success - noun, failed - verb :)

2019-05-16 06:01 UTC, lgnstn commented on app/containers/UserPage/index.js
> +  token: selectToken,
Again, too many pages now about the token.

2019-05-16 06:01 UTC, lgnstn commented on app/containers/UserPage/reducer.js
> +  name: '',
When something is missing it is better to use `null`.

2019-05-16 06:01 UTC, lgnstn commented on app/containers/UserPage/reducer.js
> +const initialState = fromJS({
I think this state should be global, at the same level with the token.

2019-05-16 06:01 UTC, lgnstn commented on app/containers/UserPage/selectors.js
> +  user.get('name'),
Please remove `,`. Please use trailing commas only in objects and arrays.

2019-05-16 06:01 UTC, lgnstn commented on app/containers/UserPage/selectors.js
> +  user.get('loading'),
Here as well.

2019-05-16 06:01 UTC, lgnstn commented on app/services/getUserRequest.js
> +    const res = await fetch(`${API_URL}/users/${id}`, {
You can create a service that hides the details of a request.

2019-05-22 07:41 UTC, lgnstn commented
@EdiOancea There are unresolved comments. Please have a look at them and try to fix those issues.

2019-05-30 06:05 UTC, lgnstn commented
@EdiOancea Is this PR ready?

2019-05-31 05:36 UTC, lgnstn requested changes

2019-05-31 05:36 UTC, lgnstn commented on app/containers/App/tests/reducer.test.js
> +  SIGN_IN_Failure,
Please use capital letters.

2019-05-31 05:36 UTC, lgnstn commented on app/containers/App/tests/reducer.test.js
> +  SIGN_IN_Failure,
@EdiOancea This one was not changed

2019-05-31 05:36 UTC, lgnstn commented on app/containers/UserPage/index.js
> +  token: selectToken,
@EdiOancea 👆

2019-05-31 05:36 UTC, lgnstn commented on app/containers/UserPage/reducer.js
> +const initialState = fromJS({
@EdiOancea ☝️

2019-05-31 05:36 UTC, lgnstn commented on app/containers/UserPage/reducer.js
> +  name: '',
@EdiOancea ☝️

2019-05-31 05:36 UTC, lgnstn commented on app/services/apiRequest.js
> +const apiRequest = async ({ url, method, headers, body }) => {
Please use simple parameters for this function in the following order: `(method, url, body = {}, headers = {})`.

2019-05-31 05:36 UTC, lgnstn commented on app/services/getUserRequest.js
> +  return {};
Please return `null` if there is no user.

2019-06-03 08:33 UTC, EdiOancea commented
@lgnstn  updated

2019-06-10 06:20 UTC, lgnstn approved these changes

2019-06-10 06:21 UTC, merged