Add company
EdiOancea/ferret-front pull request #7
Opened 2019-05-20 08:46 UTC by laurandarius

Closes #6

2019-05-20 08:48 UTC, laurandarius commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create logout "page"](https://trello.com/c/Poqu0kHD/3-create-logout-page)

2019-05-20 08:48 UTC, laurandarius commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create add company page](https://trello.com/c/OzeT7egP/4-create-add-company-page)

2019-05-22 07:52 UTC, lgnstn requested changes

2019-05-22 07:52 UTC, lgnstn commented on app/containers/AddCompanyForm/actions.js
> +  ADD_COMPANY_FAILED,
Please use the noun, "FAILURE", not the verb.

2019-05-22 07:52 UTC, lgnstn commented on app/containers/AddCompanyForm/index.js
> +    active: Yup.string(),
By default a company is active when it is created. This field shouldn't be in the form.

2019-05-22 07:52 UTC, lgnstn commented on app/containers/AddCompanyForm/index.js
> +    manager: Yup.string(),
The user that created the company is the manager, so you can remove this field from the form.

2019-05-22 07:52 UTC, lgnstn commented on app/containers/AddCompanyForm/index.js
> +    rating: Yup.string(),
The initial rating is 0. This value is going to be changed when the people that use the company's services start to rate the company.

2019-05-22 07:52 UTC, lgnstn commented on app/containers/AddCompanyForm/index.js
> +      .email('Invalid email address.')
The company name is not an email. Please remove this line.

2019-05-22 07:52 UTC, lgnstn commented on app/containers/AddCompanyForm/index.js
> +  state = {};
If you don't use the state, don't define it.

2019-05-22 07:52 UTC, lgnstn commented on app/containers/AddCompanyForm/index.js
> +  errorMessage: PropTypes.string.isRequired,
I don't think the error message is a mandatory field. Please remove the `isRequired` property.

2019-05-22 10:58 UTC, laurandarius commented
@lgnstn updated.

2019-05-23 05:44 UTC, lgnstn approved these changes

2019-05-23 05:44 UTC, merged