Create View Company page.
EdiOancea/ferret-front pull request #9
Opened 2019-05-28 12:44 UTC by laurandarius

Closes #8

2019-05-28 12:45 UTC, laurandarius commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create view company page](https://trello.com/c/MSxETnVO/6-create-view-company-page)

2019-05-30 06:05 UTC, lgnstn requested changes

2019-05-30 06:05 UTC, lgnstn commented on app/components/ViewCompanyPage/tests/index.test.js
> +        <div> a </div>
Please remove the spaces.

2019-05-30 06:05 UTC, lgnstn commented on app/components/Item/index.js
> +const Item = props => {
"Item" is a name too general and you have logic specific to a company here. Please rename it Company.

2019-05-30 06:05 UTC, lgnstn commented on app/components/Item/index.js
> +      <Table className={classes.table}>
Please avoid using tables. Build the structure you want using divs.

2019-05-30 06:05 UTC, lgnstn commented on app/components/Item/index.js
> +    return (
Empty line before `return`s please.

2019-05-30 06:05 UTC, lgnstn commented on app/components/Item/index.js
> +          {Object.entries(getItem()).map(entry => (
I'd rather add a line for each field than to iterate through all of them because it is more clear what happens. Of course, you can use a component for a line in this list.

2019-05-30 06:05 UTC, lgnstn commented on app/containers/ViewCompanyContainer/constants.js
> +export const VIEW_COMPANY = 'VIEW_COMPANY';
Please use `GET` instead of `VIEW`. You GET the company and then you can other other things too, not only view it.

2019-05-30 06:05 UTC, lgnstn commented on app/containers/ViewCompanyContainer/index.js
> +      Name: this.props.company.name,
Always use camelCase.

2019-05-30 06:05 UTC, lgnstn commented on app/containers/ViewCompanyContainer/index.js
> +    const company = {
You don't need this object. You can specify for each field its label in the component (not in container).

2019-05-30 06:05 UTC, lgnstn commented on app/containers/ViewCompanyContainer/index.js
> +    this.props.getCompanyBySlug(this.props.slug);
I don't know what you mean by slug, but it should be the id.

2019-05-30 06:05 UTC, lgnstn commented on app/containers/ViewCompanyContainer/index.js
> +    return this.props.company.id ? company : {};
This check should be before you build the `company` object.

2019-05-30 06:05 UTC, lgnstn commented on app/components/Item/index.js
> +    const item = getItem();
This is a component so it shouldn't know how to get its data. This function call should happen in the container.

2019-05-30 06:05 UTC, lgnstn commented on app/containers/ViewCompanyContainer/index.js
> +          ...this.props,
In most cases you don't want to pass all the props to a component. Please pass each prop individually. It is more clear this way.

2019-05-30 06:05 UTC, lgnstn commented on app/containers/ViewCompanyContainer/index.js
> +  getCompanyBySlug: slug => dispatch(viewCompany(slug)),
This prop is missing from propTypes. Also you can rename it `getCompany` or `fetchCompany`.

2019-05-30 06:05 UTC, lgnstn commented on app/containers/ViewCompanyContainer/reducer.js
> +  company: {},
By default the company should be `null`.

2019-05-30 06:05 UTC, lgnstn commented on app/containers/ViewCompanyContainer/index.js
> +export class ViewCompanyContainer extends React.Component {
You can remove the `Container` part from the name.

2019-05-30 06:05 UTC, lgnstn commented on app/components/ViewCompanyPage/index.js
> +const ViewCompanyPage = props => (
Please rename it `CompanyPage`.

2019-05-30 06:05 UTC, lgnstn commented on app/containers/ViewCompanyContainer/selectors.js
> +export const selectCompany = createSelector(selectViewCompany, viewCompany =>
Please indent this function the way you did for the next one.

2019-05-30 06:05 UTC, lgnstn commented on app/services/viewCompanyRequest.js
> +const viewCompanyRequest = async id => {
Please rename it `getCompanyRequest`.

2019-05-30 11:49 UTC, laurandarius commented
@lgnstn updated.

2019-05-31 05:54 UTC, lgnstn requested changes

2019-05-31 05:54 UTC, lgnstn commented on app/components/Company/index.js
> +        <div>
You can create a component for this div. As you can see, you repeat this code 5 times. This is a good sign that it is time for a new component.

2019-05-31 05:54 UTC, lgnstn commented on app/components/Company/index.js
> +  return <div className={classes.root}>{renderCompany()}</div>;
You don't need here the `renderCompany()` function. Just insert here the code.

2019-05-31 05:54 UTC, lgnstn commented on app/containers/ViewCompany/index.js
> +  constructor(props) {
You don't need this function. It already happens because you extend `React.Component`.

2019-05-31 05:54 UTC, lgnstn commented on app/components/Company/index.js
> +          <div className={classes.field}>Active</div>
The active field shouldn't be displayed. You shouldn't show inactive companies in the first place.

2019-05-31 05:54 UTC, lgnstn commented on app/components/Company/index.js
> +          <div className={classes.field}>Manager</div>
I don't think that the manager is a field that should be displayed. It doesn't matter for the users who created the profile of the company in our app.

2019-05-31 05:54 UTC, lgnstn commented on app/containers/ViewCompany/index.js
> +    return <Company company={this.formatForDisplay()} />;
Simply pass the company object here, no `formatForDisplay` function call.

2019-05-31 08:08 UTC, laurandarius commented
@lgnstn updated.

2019-06-10 06:30 UTC, lgnstn approved these changes

2019-06-10 06:31 UTC, merged